version: '2.1'

services:
  graph-visualization:
    image: graph-visualization
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js